name: Excavator

on:
  pull_request:
    paths:
      - 'bucket/*.json'
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行
  workflow_dispatch:

jobs:
  excavate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Scoop
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
      
      - name: Check for updates
        run: |
          # Scoopのcheckverヘルパーをダウンロード
          $helperPath = "$env:GITHUB_WORKSPACE\bin"
          New-Item -ItemType Directory -Force -Path $helperPath | Out-Null
          
          # Scoop-Core の checkver.ps1 をダウンロード
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/ScoopInstaller/Scoop/master/bin/checkver.ps1" -OutFile "$helperPath\checkver.ps1"
          
          # 各アプリケーションのアップデートをチェック
          $apps = Get-ChildItem ./bucket -Filter *.json | ForEach-Object { $_.BaseName }
          $hasUpdates = $false
          
          foreach ($app in $apps) {
            Write-Host "Checking $app for updates..."
            try {
              # PR時は更新せずチェックのみ、それ以外は更新
              if ($env:GITHUB_EVENT_NAME -eq 'pull_request') {
                & "$helperPath\checkver.ps1" -App "$app" -Dir "$env:GITHUB_WORKSPACE\bucket" -NoUpdate
              } else {
                & "$helperPath\checkver.ps1" -App "$app" -Dir "$env:GITHUB_WORKSPACE\bucket"
              }
              
              if ($LASTEXITCODE -eq 0) {
                Write-Host "Successfully checked $app"
                $hasUpdates = $true
              }
            } catch {
              Write-Host "Warning: Error checking ${app}: $_"
            }
          }
          
          Write-Host "Check completed."
      
      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff --cached --exit-code || git commit -m "Update apps"
      
      - name: Push changes
        if: success() && github.event_name != 'pull_request'
        run: git push